# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import platform

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

import pymysql

class Ui_MainWindow1(object):
    def messagebox(self,title,message):
        pesan = QMessageBox()
        pesan.setWindowTitle(title)
        pesan.setText(message)
        pesan.setStandardButtons(QMessageBox.Ok)
        pesan.exec_()
    def selesai(self):
        nama = self.lineEdit.text()
        alamat = self.lineEdit_2.text()
        pekerjaan = self.lineEdit_3.text()
        tujuan = self.lineEdit_4.text()
        conn = pymysql.connect(host="localhost",user="root",password="",db="db_perpustakaan2",port=3306,autocommit=True)
        cur = conn.cursor()
        query = ("insert into pengunjung(nama,alamat,pekerjaan,tujuan) values(%s,%s,%s,%s)")
        data = cur.execute(query,(nama,alamat,pekerjaan,tujuan))
        if(data):
           self.messagebox("Selamat","Data Berhasil Ditambahkan")
    def setupUi(self, Login):
        Login.setObjectName("MainWindow")
        Login.resize(800, 599)
        self.centralwidget = QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setGeometry(QRect(60, 30, 171, 31))
        self.label_2.setStyleSheet("font: 12pt \"Poppins\";\n"
"color : rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setGeometry(QRect(60, 50, 311, 31))
        self.label_3.setStyleSheet("font:  15pt \"Poppins Black\";\n"
"color :rgb(255, 255, 0)")
        self.label_3.setObjectName("label_3")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QRect(0, 0, 801, 121))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color : rgb(42, 127, 255)\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setGeometry(QRect(170, 150, 461, 431))
        self.label_4.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QRect(300, 520, 191, 41))
        self.pushButton.clicked.connect(self.selesai)
        self.pushButton.setStyleSheet("font:  10pt \"Poppins\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QRect(240, 260, 311, 31))
        font = QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:transparent;\n"
"color:black;\n"
"border:none;\n"
"border-bottom:1px solid;\n"
"font: 8pt \"Poppins\";")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(False)
        self.lineEdit.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setGeometry(QRect(300, 180, 181, 31))
        self.label_5.setStyleSheet("font:  15pt \"Poppins\";\n"
"font-weight:bold;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setGeometry(QRect(240, 240, 47, 13))
        self.label_6.setStyleSheet("font: 11pt \"Poppins\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setGeometry(QRect(240, 310, 61, 16))
        self.label_7.setStyleSheet("font: 11pt \"Poppins\";")
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QRect(240, 330, 311, 31))
        font = QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background:transparent;\n"
"color:black;\n"
"border:none;\n"
"border-bottom:1px solid;\n"
"font: 8pt \"Poppins\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setGeometry(QRect(240, 380, 81, 16))
        self.label_8.setStyleSheet("font: 11pt \"Poppins\";")
        self.label_8.setObjectName("label_8")
        self.lineEdit_3 = QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QRect(240, 400, 311, 31))
        font = QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background:transparent;\n"
"color:black;\n"
"border:none;\n"
"border-bottom:1px solid;\n"
"font: 8pt \"Poppins\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setGeometry(QRect(240, 450, 81, 16))
        self.label_9.setStyleSheet("font: 11pt \"Poppins\";")
        self.label_9.setObjectName("label_9")
        self.lineEdit_4 = QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QRect(240, 470, 311, 31))
        font = QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background:transparent;\n"
"color:black;\n"
"border:none;\n"
"border-bottom:1px solid;\n"
"font: 8pt \"Poppins\";")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.lineEdit_2.raise_()
        self.label_8.raise_()
        self.lineEdit_3.raise_()
        self.label_9.raise_()
        self.lineEdit_4.raise_()
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Selamat Datang"))
        self.label_3.setText(_translate("MainWindow", "Perpustakaan Zharmedia"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Nama.."))
        self.label_5.setText(_translate("MainWindow", "Buku Pengunjung"))
        self.label_6.setText(_translate("MainWindow", "Nama"))
        self.label_7.setText(_translate("MainWindow", "Alamat"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Alamat..."))
        self.label_8.setText(_translate("MainWindow", "Pekerjaan"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Pekerjaan..."))
        self.label_9.setText(_translate("MainWindow", "Tujuan"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Tujuan..."))


# if __name__ == "__main__":
#     import sys
#     app = QApplication(sys.argv)
#     MainWindow = QMainWindow()
#     ui = Ui_MainWindow1()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
