# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

import pymysql
from formInput import Ui_MainWindow1

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 594)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QRect(0, 0, 801, 121))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color : rgb(42, 127, 255)\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setGeometry(QRect(60, 30, 171, 31))
        self.label_2.setStyleSheet("font: 12pt \"Poppins\";\n"
"color : rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setGeometry(QRect(60, 50, 311, 31))
        self.label_3.setStyleSheet("font:  15pt \"Poppins Black\";\n"
"color :rgb(255, 255, 0)")
        self.label_3.setObjectName("label_3")
        self.toolButton_2 = QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QRect(370, 170, 81, 81))
        self.toolButton_2.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border-radius:40px;")
        icon = QIcon()
        icon.addPixmap(QPixmap("../../../../../Foto/Pictures/Logo/Icon BW/Account.png"), QIcon.Normal, QIcon.Off)
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setIconSize(QSize(50, 50))
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setGeometry(QRect(250, 210, 311, 281))
        self.label_4.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QRect(310, 310, 191, 31))
        font = QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        # font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background:transparent;\n"
"color:black;\n"
"border:none;\n"
"border-bottom:1px solid;\n"
"font: 8pt \"Poppins\";")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(False)
        self.lineEdit.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QRect(310, 370, 191, 31))
        font = QFont()
        font.setFamily("Poppins")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        # font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background:transparent;\n"
"color:black;\n"
"border:none;\n"
"border-bottom:1px solid;\n"
"font: 8pt \"Poppins\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setEchoMode(QLineEdit.Password)
        self.lineEdit_2.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setGeometry(QRect(380, 260, 61, 31))
        self.label_5.setStyleSheet("font:  15pt \"Poppins\";")
        self.label_5.setObjectName("label_5")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QRect(310, 420, 191, 41))
        self.pushButton.setStyleSheet("font:  10pt \"Poppins\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.toolButton_2.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label_5.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Selamat Datang"))
        self.label_3.setText(_translate("MainWindow", "Perpustakaan Zharmedia"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Username.."))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password.."))
        self.label_5.setText(_translate("MainWindow", "Login"))
        self.pushButton.setText(_translate("MainWindow", "Login"))


# if __name__ == "__main__":
#     import sys
#     app = QApplication(sys.argv)
#     MainWindow = QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
